DROP TABLE "items";

CREATE TABLE "items" (
	"id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"item" TEXT NOT NULL,
	"description" TEXT NOT NULL,
	"created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"updated_at" DATETIME DEFAULT CURRENT_TIMESTAMP
);
